config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :foods
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "foods#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
# frozen_string_literal: true

class Food < ApplicationRecord
  belongs_to :user

  def self.sum_calories(user)
    user.foods.sum(:calories)
  end

  def self.sum_weight(user)
    user.foods.sum(:weight)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :foods
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/foods_controller.rb
# frozen_string_literal: true

class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :destroy, :update]
  def index
    @foods = current_user.foods
    @calories = Food.sum_calories(current_user)
    @weight = Food.sum_weight(current_user)
    # binding.pry
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(foods_params)
    if @food.save
      redirect_to foods_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @food.update(foods_params)
      redirect_to foods_path
    else
      render :edit
    end
  end
  def show; end

  def destroy
    @food.destroy
    redirect_to foods_path
  end

  private

  def set_food
    @food = current_user.foods.find(params[:id])
  end

  def foods_params
    params.require(:food).permit(:name, :weight, :calories, :ingredient, :bestby)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<%= form_with(model:@food, local: true, placeholder:'Delicious Thing') do |f| %>
<div class= 'form-squish'>
<div class='field'>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, focus: true, placeholder: 'name of the food'%>
  </div>
  <div class='field'>
  <%= f.label :calories %>
  <%= f.number_field :calories %>
  </div>
  <div class='field'>
  <%= f.label :weight%>
  <%= f.number_field :weight, placeholder:'in grams' %>
  </div>
  <div class='field'>
  <%= f.label :ingredient%>
  <%= f.text_field :ingredient, placeholder:'add ingredients for more complex foods'%>
  </div>
  <%= f.submit %>
  <% end %>
  </div>

app/views/foods/edit.html.erb
<h1>Foods#edit</h1>
<%= render 'form' %>

app/views/foods/index.html.erb
<h4>Shopping List<h4>
<h5><%= link_to "New food Item", new_food_path %></h5>

<table class="form-squish">
  <thead>
    <tr>
      <th>purchased?</th>
      <th>Name</th>
      <th>Calories</th>
      <th>Weight(g)</th>
      <th>Ingredients</th>
      <th>delete/edit</th>
    </tr>
  </thead>
    <% @foods.each do |food| %>
  <tbody>
    <tr>
      <td></td>
      <td><%= "#{food.name}"%></td>
      <td><%="#{food.calories} C" %></td>
      <td><%="#{food.weight}g" %></td>
      <td><%="#{food.ingredient}" %></td>
      <td><%= link_to "delete", food_path(food), method: :delete%>/
      <%= link_to 'edit', edit_food_path(food)%></td>
    </tr>
  <% end%>
  <tr>
    <td></td>
    <td></td>
    <td class='thick'>Total Calories</td>
    <td class='thick'>Total Weight</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td class='thick'><%= "#{@calories} C" %></td>
    <td class='thick'><%= "#{@weight}g" %></td>
    <td></td>
    <td></td>
  </tr>
  </tbody>
</table>

app/views/foods/new.html.erb
<h1>Add to the list</h1>
<%= render 'form' %>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<p>Find me in app/views/foods/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="#" class="brand-logo">
      <%= link_to 'app', root_path %>
    </a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% if user_signed_in? %>
        <li>
          <%= link_to "accounts"%>
        </li>
        <li>
          <%= link_to "logout", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to 'login', new_user_session_path %>
        </li>
        <li>
          <%= link_to 'sign up', new_user_registration_path%>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>DeviseProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>

</html>